# Generated by Django 5.2 on 2025-05-05 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=12)),
                ("date_range", models.CharField(max_length=12)),
                ("year", models.CharField(max_length=4)),
                ("pay_cycle", models.CharField(max_length=12)),
                ("rate", models.FloatField()),
                ("earnings_allowance", models.FloatField()),
                ("deductions_tax", models.FloatField()),
                ("deductions_health", models.FloatField()),
                ("pag_ibig", models.FloatField()),
                ("sss", models.FloatField()),
                ("overtime", models.FloatField()),
                ("total_pay", models.FloatField()),
                (
                    "id_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll_app.employee",
                    ),
                ),
            ],
        ),
    ]
