# Generated by Django 5.2 on 2025-05-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_app", "0003_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="rate",
            field=models.FloatField(default=0.0),
        ),
    ]
