# Generated by Django 5.2 on 2025-05-12 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_app", "0004_employee_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payroll_app.account",
            ),
        ),
    ]
